version: "3.9"
services:
    db:
        image: postgres:15
        restart: unless-stopped
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?error}
            - POSTGRES_USER=${POSTGRES_USER?error}
        ports:
            - 5432
        volumes:
            - /opt/mamall-db:/var/lib/postgresql/data
            - ./mamall-back/db/migrations/:/docker-entrypoint-initdb.d/
        networks:
          mamall_private:
            ipv4_address: 172.16.239.11
    
    rest:
        build: 
          context: ./mamall-back/
          dockerfile: DockerfileRest
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?error}
            - POSTGRES_USER=${POSTGRES_USER?error}
            - POSTGRES_PORT=${POSTGRES_PORT?error}
            - POSTGRES_DB=${POSTGRES_DB?error}
            - POSTGRES_SCHEMA=${POSTGRES_SCHEMA?error}
            - PGHOST=${PGHOST?error}
            - CORSORIGIN=${CORSORIGIN?error}
            - JWTSECRET=${JWTSECRET?error}
        user: 1000:1000
        ports:
            - 8080
        depends_on:
            - db
        networks:
          mamall_public:
            ipv4_address: 172.16.238.9
          mamall_private:
            ipv4_address: 172.16.239.9

    signaling:
        build: 
          context: ./mamall-back/
          dockerfile: DockerfileSignal
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?error}
            - POSTGRES_USER=${POSTGRES_USER?error}
            - POSTGRES_PORT=${POSTGRES_PORT?error}
            - POSTGRES_DB=${POSTGRES_DB?error}
            - POSTGRES_SCHEMA=${POSTGRES_SCHEMA?error}
            - PGHOST=${PGHOST?error}
            - MEDIASOUP_LISTEN_IP=${MEDIASOUP_LISTEN_IP?error}
            - MEDIASOUP_ANNOUNCED_IP=${MEDIASOUP_ANNOUNCED_IP?error}
            - CORSORIGIN=${CORSORIGIN?error}
            - JWTSECRET=${JWTSECRET?error}
        user: 1000:1000
        ports:
            - 7001
            - 11111:11111/udp
            - 11111:11111
        depends_on:
            - db
        networks:
          mamall_public:
            ipv4_address: 172.16.238.10
          mamall_private:
            ipv4_address: 172.16.239.10
    frontend:
        build: 
          context: ./mamall-front/
          args:
            HTTPHOST: ${HTTPHOST?error}
            WSHOST: ${WSHOST?error}
            VALIDATEPATH: ${VALIDATEPATH?error}
            REFRESHPATH: ${REFRESHPATH?error}
        user: 1000:1000
        ports:
            - 3000
        networks:
          mamall_public:
            ipv4_address: 172.16.238.11

networks:
  mamall_public: 
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
  mamall_private:
    ipam:
      driver: default
      config:
        - subnet: "172.16.239.0/24"
