version: "3.9"
services:
    db:
        image: postgresql...
    
    stun-server:
        build: ./mamall-back/
        user: 1000:1000
        ports:
            - "3478:3478/udp"
            - "80:80"
            - "8000:8000"
        volumes:
            - ./mamall-back:/app/src/